### ISSUE TITLE
link to push-ios-heartbeatmonitor no longer exists

### ISSUE THREAD

**Issue by phopper-pivotal** [cfmobile/docs-push-notifications#55]
when running command, results in repository not found

$ git clone git@github.com:cfmobile/push-ios-heartbeatmonitor.git
Cloning into 'push-ios-heartbeatmonitor'...
Enter passphrase for key '/Users/phopper/.ssh/id_rsa': 
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jncd** [comment]
Hi @xtremerui Can you help with this issue? What happened to the push-ios-heartbeatmonitor repo?
TIA, jane

**Comment by xtremerui** [comment]
@jncd this repo is private. We will either hide the reference in the doc or make it public again.

**Comment by xtremerui** [comment]
Will make cfmobile/push-ios-heartbeatmonitor.git and cfmobile/push-android-heartbeatmonitor.git public. Story is created https://www.pivotaltracker.com/story/show/151214384.

**Comment by jncd** [comment]
@xtremerui Thanks! (V. helpful to have the story link.)

**Comment by xtremerui** [comment]
ios/android heartbeat monitor app are now public. Closing issue.

**Comment by jncd** [comment]
Thank you @xtremerui 
I'm closing the tracker issue associated with this too.
