### ISSUE TITLE
Error "cannot access MiPushMessage" after integrating Baidu dependency

### ISSUE THREAD

**Issue by aswini149** [cfmobile/docs-push-notifications#56]
To integrate Baidu push notification, after adding the dependency like;

compile 'io.pivotal.android:push-baidu:1.9.0'

not able to run the application, getting error 
"cannot access MiPushMessage"

**Comment by aswini149** [comment]
Just a comment, 
the error message goes away when i add MiPush_SDK_Client_3_4_5.jar file to the project.

But when testing i am receiving two notifications, one through the overridden onNotoficationArrived() method and other not sure (May be from default Baidu)

How to avoid the other default notification ?

**Comment by jncd** [comment]
Hi @xtreme-matthew-smith , Are you able to help @aswini149 with his query and comment? 
(Make a PR if you need anything added to the docs.)
tia, Jane

**Comment by xtreme-matthew-smith** [comment]
@aswini149 Please submit a support ticket here: https://support.pivotal.io/ and we will get you sorted and after the resolution we'll add more troubleshooting to the docs.

Thanks!
